from ui.settings import Header, Switch, Divider
from elyx import strings


def build_misc_page(other_settings):
    return [
        Header(text=strings.misc_header),
        Switch(
            key="show_startup_status",
            text=strings.show_startup_status,
            subtext=strings.show_startup_status_desc,
            default=False,
            icon="msg_info",
            link_alias="show_startup_status"
        ),
        Switch(
            key="fuzzy_search",
            text=strings.fuzzy_search,
            subtext=strings.fuzzy_search_desc,
            default=True,
            icon="msg_search",
            link_alias="fuzzy_search"
        ),
        Switch(
            key="live_search",
            text=strings.live_search,
            subtext=strings.live_search_desc,
            default=True,
            icon="msg_search",
            link_alias="live_search"
        ),
        Switch(
            key="static_online_status",
            text=strings.static_online_status,
            subtext=strings.static_online_status_desc,
            default=False,
            icon="msg_online",
            link_alias="static_online_status"
        ),
        Switch(
            key="show_from_repo",
            text=strings.show_from_repo,
            subtext=strings.show_from_repo_desc,
            default=False,
            icon="msg_channel",
            link_alias="show_from_repo"
        ),
        Switch(
            key="disable_achievements_notify",
            text=strings.disable_achievements_notify,
            subtext=strings.disable_achievements_notify_desc,
            default=False,
            icon="msg_gift_premium",
            link_alias="disable_achievements_notify"
        ),
        Divider(),
        Header(text=strings.repos_navigation_header),
        Switch(
            key="skip_repository_selection",
            text=strings.skip_repository_selection,
            subtext=strings.skip_repository_selection_desc,
            default=False,
            icon="msg_leave",
            link_alias="skip_repository_selection"
        ),
        Switch(
            key="version_picker_auto_expand",
            text=strings.version_picker_auto_expand,
            subtext=strings.version_picker_auto_expand_desc,
            default=False,
            icon="msg_list",
            link_alias="version_picker_auto_expand"
        ),
        Divider(text=strings.navigation_header_desc),
        Header(text=strings.install_sheet_header),
        Switch(
            key="install_sheet_links",
            text=strings.install_sheet_links,
            subtext=strings.install_sheet_links_desc,
            default=True,
            icon="msg_link",
            link_alias="install_sheet_links"
        ),
        Switch(
            key="install_sheet_hash",
            text=strings.install_sheet_hash,
            subtext=strings.install_sheet_hash_desc,
            default=True,
            icon="msg_sendfile",
            link_alias="install_sheet_hash"
        ),
        Switch(
            key="install_sheet_signatures",
            text=strings.install_sheet_signatures,
            subtext=strings.install_sheet_signatures_desc,
            default=True,
            icon="msg_policy",
            link_alias="install_sheet_signatures"
        ),
        Divider(),
    ]
