name: PackIt
description: "{plugin_description} [shareui/packit-source](https://github.com/shareui/packit-source)"
id: shareui_packit
version: "0.1.1-dev.19"
author: "@packitX"
app_version: ">=12.9.0"
sdk_version: ">=1.4.5.0"
icon: plugin232/17
