name: PackIt
description: "{plugin_description} [shareui/packit-source](https://github.com/shareui/packit-source)"
id: shareui_packit
version: "1.0.0-dev.1414"
author: "@packitX"
app_version: ">=12.5.1"
sdk_version: ">=1.4.3.2"
elyx_version: ">=0.9.0"
icon: plugin232/17

# кстати тебя врядли выложат в utilits. Ты пофакту, повторил kpm. А как бы в utils правило второй вариант нельзя выкладыватьб
