name: PackIt
description: |
  **A resource catalog for exteraGram/AyuGram. Plugins, icons, configs — all in one place, with support for multiple repositories.**
id: shareui_packit
version: "1.0.0-dev.441"
author: "@packitapp"
min_version: "12.4.1"
icon: plugin232/17
